### PR TITLE
[WIP] Shorthand support

### PR DESCRIPTION
**Pull request by Krizzu**
Currently, support for `margin`, `padding`, `borderRadius`, `shadowOffset`.

### CODE REVIEW

**Comment by vitalets** [comment]
See: https://github.com/vitalets/react-native-extended-stylesheet/issues/69#issuecomment-351024783

**Comment by gurs1kh** [comment]
Any help needed to get this done? This feature would be very useful.

**Comment by vitalets** [comment]
> Any help needed to get this done? This feature would be very useful.

Yes, help is welcome. Please have a look on this comment https://github.com/vitalets/react-native-extended-stylesheet/issues/69#issuecomment-351024783.

**Comment by Krizzu** [comment]
Totally forgot about this one :D @gurs1kh If you would like to have a second look (or close this one and open new PR) feel free to 👍

**Pull request closed without merging**
