### PR TITLE
Add 'left', 'right', 'bottom', 'up' to SCALABLE_PROPS

### PR DESCRIPTION
**Pull request by SNY7**

### CODE REVIEW

**Comment by vitalets** [comment]
hi @SNY7 !
Could you share your experience is scaling positioning props always needed? 
Maybe in some cases only sizing props should be scaled.

**Comment by SNY7** [comment]
@vitalets It's only used in absolute positioning, otherwise elements' position will shifting. Very useful in my projects.

**Comment by vitalets** [comment]
I'm concerning will not it break the layout.
@SNY7 could you show an example?

**Comment by SNY7** [comment]
@vitalets I use it for something absolute elements, for example:

**Pull request closed without merging**
